In [1]:
# For API calls and response parsin
import pandas as pd
import requests
from pprint import pprint

# For connecting to Supabase
from sqlalchemy import create_engine
from sqlalchemy.dialects.postgresql import JSONB
from dotenv import load_dotenv
import os

# For parsing responses
from datetime import datetime, timezone

# For Mastering
import re
import unicodedata 
from rapidfuzz import fuzz, process

In [ ]:
url = "https://clinicaltrials.gov/api/v2/studies"
params={"query.cond": "non-small cell lung cancer",
        "pageSize": 1000,
        "filter.advanced": "AREA[StartDate]2022"}
response = requests.get(url, params)
study = response.json()

# Raw Layer

### Preparing the Table

In [2]:
RAW_COLUMNS = ["nct_id", "raw_json", "fetched_at", "params", "response_url"]

def raw_builder(response: requests.Response, params: dict) -> pd.DataFrame:
    """Build raw-layer rows (one per study) from a ClinicalTrials.gov API response."""
    response.raise_for_status()
    studies = response.json()["studies"]

    fetched_at = datetime.now(timezone.utc)
    params = dict(params)  # snapshot, so later mutation doesn't leak into stored rows

    return pd.DataFrame(
        [
            {
                "nct_id": s["protocolSection"]["identificationModule"]["nctId"],
                "raw_json": s,
                "fetched_at": fetched_at,
                "params": params,
                "response_url": response.url,
            }
            for s in studies
        ],
        columns=RAW_COLUMNS,
    )

### Writing it To Supabase

In [3]:
client = create_engine(os.getenv("SUPABASE_PROJECT_URL"))

raw_table = raw_builder(response, params)

NameError: name 'response' is not defined

In [4]:
if False:
    raw_table.to_sql("raw_responses",
                    con=client,
                    schema="raw",
                    if_exists="replace",
                    dtype={"raw_json": JSONB, "params": JSONB},
                    index=False)

# Study Tables

## Study Master

Columns:
  - [x] nct_id (primary key)
  - [x] study_title
  - [x] study_long_title
  - [x] study_acronym
  - [] sponsor_id (foreign key)
  - [] compound_id (foreign key)
  - [] company_id (foreign key)
  - [x] lead_sponsor
  - [] collaborator_id
  - [x] collaborator_names
  - [x] study_type
  - [x] conditions

Function:
  - parse_study_master --> takes the JSON response as input, flattens and extracts the variables in to a table

In [ ]:
# Flattener func
def extract_study_master(study: dict) -> dict:
    '''Flattens the study dictionary of the JSON API response into a single dictionary to turn into a DataFrame'''
    id_mod = study['protocolSection'].get("identificationModule", {})
    sponsor_mod = study['protocolSection'].get("sponsorCollaboratorsModule", {})
    cond_mod = study['protocolSection'].get("conditionsModule", {})
    outcome_mod = study['protocolSection'].get("outcomesModule", {})
    status_mod = study['protocolSection'].get("statusModule", {})
    design_mod = study['protocolSection'].get("designModule", {})

    extracted_dict = {
        "nct" : id_mod.get("nctId"),
        "study_title": id_mod.get("briefTitle"),
        "study_long_title": id_mod.get("officialTitle"),
        "study_acronym": id_mod.get("acronym"),
        "lead_sponsor": sponsor_mod.get("leadSponsor", {}).get("name"),
        "collaborators:": parse_collaborators(sponsor_mod),
        "endpoints": outcome_mod.get("outcomesModule"),
        "status": status_mod.get("overallStatus"),
        "study_type": design_mod.get('studyType'),
        "conditions": cond_mod.get("conditions")
    }
    
    return extracted_dict

# Parser for extracting collaborators
def parse_collaborators(x):
    '''Extracts the collaborators from the collaborators portion of the protocolSection'''
    try:
        return ': '.join(a.get('name') for a in x.get("collaborators"))
    except:
        return None

In [ ]:
test_results = pd.DataFrame.from_dict([extract_study_master(s) for s in study['studies']])

# Sponsor Tables

## Sponsor Master

In [5]:
# Sets of strings to strip from sponsor and collaborator names
LEGAL = {"inc", "incorporated", "corp", "corporation", "co", "company", "ltd", "limited",
         "llc", "lp", "plc", "gmbh", "ag", "sa", "nv", "bv", "kk"}
GENERIC = {"pharmaceuticals", "pharma", "therapeutics", "biosciences", "biopharma",
           "labs", "laboratories", "laboratory", "holdings", "group"}

# Function to process sponsor names into tokens for mastering
def create_sponsor_tokens(sponsor_name: str) -> list[str]:
    '''Takes sponsor name, removes accents, non-ASCII characters, converts it to
     plain lower-case text, replaces special characters punctuation with spaces.
     
     Returns a list of processes sponsor name tokens'''
    s = unicodedata.normalize("NFKD", sponsor_name).encode("ascii", "ignore").decode().lower()
    s = s.replace("&", " and ")
    s = re.sub(r"[^\w\s]", " ", s)
    return s.split()

# Function to create a strict sponsor name key
def create_strict_key(sponsor_name: str) -> str:
    '''Takes raw sponsor name, applies create_function_tokens, removes legal string
    and returns a single string'''
    return " ".join(t for t in create_sponsor_tokens(sponsor_name) if t not in LEGAL)

# Function to create loose sponsor name key
def create_loose_key(sponsor_name: str) -> str:
    '''Takes raw sponsor name, applies create_function_tokens, removes generic strings
    and returns a single string'''
    return " ".join(t for t in create_sponsor_tokens(sponsor_name) if t not in LEGAL | GENERIC)

In [6]:
# Pulling the sponsors table from the staging layer
sponsor_names = pd.read_sql(
    """select raw_name,
    sponsor_class,
    count(*) as total_mentions
    from staging.sponsors
    where raw_name is not null
    group by raw_name, sponsor_class
    order by count(*) desc""",
    client)

In [7]:
# Assigning new columns in the table after applying strict and loose key functions
sponsor_names['strict_key'] = sponsor_names['raw_name'].apply(create_strict_key)
sponsor_names['loose_key'] = sponsor_names['raw_name'].apply(create_loose_key)

In [8]:
groups = sponsor_names.groupby('strict_key')
exact = sponsor_names.assign(cluster=groups.ngroup())

### Greedy Algorithm for Finding Potential Matches

In [9]:
reps = exact.drop_duplicates("cluster")[["cluster", "raw_name", "loose_key", "total_mentions", "sponsor_class"]]

AUTO, REVIEW = 92, 80
auto_pairs, review_pairs = [], []

choices = reps.loose_key.to_list()

for i, row in reps.iterrows():
    established = reps[reps.total_mentions > row.total_mentions]
    
    if established.empty:
        continue
    best = process.extractOne(row.loose_key, established.loose_key.to_list(), scorer=fuzz.token_sort_ratio)

    if not best: 
        continue
    match_text, score, idx = best
    target = established.iloc[idx]
    if row.sponsor_class != target.sponsor_class:
        continue
    rec = (row.cluster, target.cluster, score)
    (auto_pairs if score >= AUTO else review_pairs if score >= REVIEW else []).append(rec)

In [10]:
# Example for inspecting a review pair
(reps[reps.cluster == review_pairs[0][0]]['raw_name'], reps[reps.cluster == review_pairs[0][1]]['raw_name'])

(49    Peking University Cancer Hospital & Institute
 Name: raw_name, dtype: str,
 6    Tianjin Medical University Cancer Institute an...
 Name: raw_name, dtype: str)

### Writing Master Tables to the Database

In [11]:
sponsor_master_records = reps.loc[:, ['raw_name', 'sponsor_class']].rename(columns={"raw_name": "canonical_name",
                                                                                    "sponsor_class": "class"})

In [12]:
if False:
    sponsor_master_records.to_sql("sponsor",
                                client,
                                schema="master",
                                if_exists="append",
                                index=False)

### Building the Crosswalk Table

In [19]:
ids = pd.read_sql("""
select *
from master.sponsor""",
client)

In [26]:
sponsor_names

,raw_name,sponsor_class,total_mentions,strict_key,loose_key
0,AstraZeneca,INDUSTRY,22,astrazeneca,astrazeneca
1,Merck Sharp & Dohme LLC,INDUSTRY,15,merck sharp and dohme,merck sharp and dohme
2,National Cancer Institute (NCI),NIH,13,national cancer institute nci,national cancer institute nci
3,Bristol-Myers Squibb,INDUSTRY,8,bristol myers squibb,bristol myers squibb
4,Novartis Pharmaceuticals,INDUSTRY,8,novartis pharmaceuticals,novartis
...,...,...,...,...,...
522,"Palleon Pharmaceuticals, Inc.",INDUSTRY,1,palleon pharmaceuticals,palleon
523,IQVIA Pty Ltd,INDUSTRY,1,iqvia pty,iqvia pty
524,Vall d'Hebron Institute of Oncology,OTHER,1,vall d hebron institute of oncology,vall d hebron institute of oncology
525,Faeth Therapeutics,INDUSTRY,1,faeth therapeutics,faeth
526,Ascendis Pharma Oncology Division A/S,INDUSTRY,1,ascendis pharma oncology division a s,ascendis oncology division a s

In [30]:
exact.merge(ids[['canonical_name', 'sponsor_id']], left_on="raw_name", right_on="canonical_name")

,raw_name,sponsor_class,total_mentions,strict_key,loose_key,cluster,canonical_name,sponsor_id
0,AstraZeneca,INDUSTRY,22,astrazeneca,astrazeneca,38,AstraZeneca,1
1,Merck Sharp & Dohme LLC,INDUSTRY,15,merck sharp and dohme,merck sharp and dohme,291,Merck Sharp & Dohme LLC,2
2,National Cancer Institute (NCI),NIH,13,national cancer institute nci,national cancer institute nci,297,National Cancer Institute (NCI),3
3,Bristol-Myers Squibb,INDUSTRY,8,bristol myers squibb,bristol myers squibb,68,Bristol-Myers Squibb,4
4,Novartis Pharmaceuticals,INDUSTRY,8,novartis pharmaceuticals,novartis,312,Novartis Pharmaceuticals,5
...,...,...,...,...,...,...,...,...
522,"Palleon Pharmaceuticals, Inc.",INDUSTRY,1,palleon pharmaceuticals,palleon,322,"Palleon Pharmaceuticals, Inc.",523
523,IQVIA Pty Ltd,INDUSTRY,1,iqvia pty,iqvia pty,235,IQVIA Pty Ltd,524
524,Vall d'Hebron Institute of Oncology,OTHER,1,vall d hebron institute of oncology,vall d hebron institute of oncology,491,Vall d'Hebron Institute of Oncology,525
525,Faeth Therapeutics,INDUSTRY,1,faeth therapeutics,faeth,124,Faeth Therapeutics,526
526,Ascendis Pharma Oncology Division A/S,INDUSTRY,1,ascendis pharma oncology division a s,ascendis oncology division a s,35,Ascendis Pharma Oncology Division A/S,527